---
version: 2

registries:
  java-private-library-maven:
    type: maven-repository
    url: https://maven.pkg.github.com/octodemo/java-private-library
    username: octodemobot
    password: ${{ secrets.OCTODEMO_OCTODEMOBOT_GHPR_TOKEN }}

  npm-github:
    type: npm-registry
    url: https://npm.pkg.github.com
    token: ${{ secrets.OCTODEMO_OCTODEMOBOT_GHPR_TOKEN }}

updates:
  - package-ecosystem: maven
    directory: "java"
    registries:
      - "java-private-library-maven"
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: "/nodejs"
    registries:
      - "npm-github"
    schedule:
      interval: daily
