---
version: 2

registries:
  java-private-library-maven:
    type: maven-repository
    url: https://maven.pkg.github.com/octodemo/java-private-library
    username: octodemobot
    password: ${{ secrets.OCTODEMOBOT_PACKAGES_PAT }}

  npm-github:
    type: npm-registry
    url: https://npm.pkg.github.com
    token: ${{ secrets.OCTODEMOBOT_PACKAGES_PAT }}

updates:
  - package-ecosystem: maven
    directory: "/java"
    registries:
      - "java-private-library-maven"
    schedule:
      interval: daily
    versioning-strategy: auto

  - package-ecosystem: npm
    directory: "/nodejs"
    schedule:
      interval: daily
    versioning-strategy: auto