name: Java - CI with Maven

on:
  push:
    paths: 
      - java/**
      - .github/workflows/java_build.yml

  pull_request_target:
    paths: 
      - java/**

jobs:
  build:
    name: Build and Publish
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        
        server-id: github
        server-username: MAVEN_USERAME
        server-password: MAVEN_GHPR_PASSWORD
              
    - name: Build with Maven
      env:
        MAVEN_USERNAME: octodemobot
        MAVEN_GHPR_PASSWORD: ${{ secrets.OCTODEMO_OCTODEMOBOT_TOKEN }}
      working-directory: java
      run: |
        mvn -B package --file pom.xml