name: Java - CI with Maven - Dependabot

on:
  pull_request_target:
    paths:
       - java/**/pom.xml

jobs:
  build:
    name: Build and Publish
    if: contains(github.event.pull_request.labels.*.name, 'dependencies') && contains(github.event.sender.login, 'dependabot')

    runs-on: ubuntu-20.04

    steps:
      - name: Display Context
        uses: actions/github-script@v3
        with:
          script: |
            core.startGroup('Context');
            core.info(`Event: ${context.eventName}`);
            core.info(`Payload:`);
            core.info(JSON.stringify(context.payload, null, 2));
            core.endGroup();

      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          ref: ${{ github.event.pull_request.head.sha }}
        
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          
          server-id: github
          server-username: MAVEN_USERAME
          server-password: MAVEN_GHPR_PASSWORD

      # Utilize caching of the resolved plugins and dependencies from previous Maven builds to provide
      # faster builds when dependencies have not changed.
      - name: Cache Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          # Hash on the POM file as that would need to change to modify the dependencies or plugins in use
          key: mvn-${{ matrix.java }}-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            mvn-${{ matrix.java }}-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
            mvn-${{ matrix.java }}-${{ runner.os }}
            mvn-${{ matrix.java }}
            mvn-

      - name: Show dependencies
        env:
          MAVEN_USERNAME: octodemobot
          MAVEN_GHPR_PASSWORD: ${{ secrets.OCTODEMO_OCTODEMOBOT_TOKEN }}
        working-directory: java
        run: |
          mvn -B dependency:tree --file pom.xml

      - name: Build with Maven
        env:
          MAVEN_USERNAME: octodemobot
          MAVEN_GHPR_PASSWORD: ${{ secrets.OCTODEMO_OCTODEMOBOT_TOKEN }}
        working-directory: java
        run: |
          mvn -B package --file pom.xml