name: Node.js - Build and Test

on:
  push:
    paths: 
      - nodejs/**

  pull_request_target:
    paths:
       - nodejs/**

jobs:
  build_and_test:
    name: Build and Test

    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '12.x'
          registry-url: 'https://npm.pkg.github.com'

      - name: npm ci
        run: npm ci

      - name: npm test
        run: npm test
