name: Node.js - Build and Test

on:
  push:
    paths: 
      - nodejs/**
      - .github/workflows/nodejs_build.yml

  pull_request_target:
    paths:
       - nodejs/**

jobs:
  build_and_test:
    name: Build and Test

    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '12.x'

      - name: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secret.OCTODEMO_OCTODEMOBOT_GHPR_TOKEN }}
        working-directory: nodejs
        run: npm ci

      - name: npm test
        working-directory: nodejs
        run: npm test
